version: '3.8'


services:
  db:
    imagine: postgres:15
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - PROSTGRES_HOST_AUTH_METHOD=trust
    command: postgres -c listen_addresses='*'
volumes:
  postgres_data:
